### ISSUE TITLE
Include the list of permissions needed in the README

### ISSUE THREAD

**Issue by marcogiorgio** [Red-Swingline/OPNsenseManager#12]
Hi,
Since the app requires an API key to work, it would be useful to include the list of permissions needed by the app in the README file.
Additionally, I've noticed that the URL pointing to the firewall plugin docs in the README is broken.
Thanks!

**Comment by Red-Swingline** [comment]
README has been updated to fix the link and include a minimum group permissions table for current features.

**Comment by marcogiorgio** [comment]
> README has been updated to fix the link and include a minimum group permissions table for current features.

Thanks!
I've tried with these permissions but I get the error `an exeption error occurred` whenever I try to load one menu item...

```
 	GUI 	Dashboard (all)
	GUI 	Diagnostics: ARP Table
	GUI 	Diagnostics: Reboot System
	GUI 	Firewall: Alias: Edit
	GUI 	Firewall: Rules
	GUI 	Status: Services
```
I couldn't find these permissions that you included in the README:
```
GUI Dashboard (widgets only)
GUI Firewall: Rules: API
```
Maybe we are running different OPNsense versions? (I am on 22.7.3_1)

**Comment by Red-Swingline** [comment]
I was testing against an old VM I have updated the permissions in the push to 3.0.1
