### ISSUE TITLE
Error and request.

### ISSUE THREAD

**Issue by yeraycito** [Red-Swingline/OPNsenseManager#16]
First of all, thank you for your application and for the renewal you have given it in the last few days. I have installed version 3.0.1 on my Samsung S21 with Android 14 and when I open it for the first time it still gives the warning that the application is developed for previous versions of Android. After accepting the warning the application works fine.
The request is to see if you can develop it also for IOS, it would be greatly appreciated and of course don't forget to keep developing it adding more features if possible.

**Comment by Red-Swingline** [comment]
I am aware of the SDK version warning. It should be bumped in the next release.


An ISO version is likely not going to happen, I would have to charge as its not free for a developer licence and there isn't an official way to sign and distribute installable packages for side loading. I don't own an Iphone or Ipad to do any functional testing outside of emulator.

**Comment by Red-Swingline** [comment]
Warning should be taken care of with the last release
