### ISSUE TITLE
Restart does not work.

### ISSUE THREAD

**Issue by yeraycito** [Red-Swingline/OPNsenseManager#18]
v3.0.2 android 14 - opnsense 24.7.4

When executing an opnsense restart from the application the application crashes and the restart does not occur.

**Comment by Red-Swingline** [comment]
I'll look at this later this evening.

**Comment by Red-Swingline** [comment]
Fixed in 3.0.3

https://github.com/Red-Swingline/OPNsenseManager/releases/tag/v3.0.3
