### ISSUE TITLE
Profile issues

### ISSUE THREAD

**Issue by paour** [Red-Swingline/OPNsenseManager#19]
In the current version (3.0.3, Android), profiles are not easy to use:

- updating a profile doesn't save the changes
- updating a profile generates a duplicate profile (with the same data)
- deleting one of the duplicates deletes all of them

**Comment by Red-Swingline** [comment]
I am unable to recreate this, did you upgrade from 3.0.0 , .1 or .2?

**Comment by paour** [comment]
I think I installed .1 first, then .2 and .3. I can clear storage to test if you think the upgrade path may have corrupted the config.

**Comment by Red-Swingline** [comment]
I didn't do much testing of DB migration between those versions.

**Comment by paour** [comment]
Following a reset of app data, the issue is no longer present.
