### ISSUE TITLE
No firewall rules showing

### ISSUE THREAD

**Issue by TryAnixx** [Red-Swingline/OPNsenseManager#20]
I got some Firewall rules in my opnsense.

But the app shows no firewall rules.

is it possible to integrate NAT Port forwarding rules?

**Comment by Red-Swingline** [comment]
The normal firewall rules aren't exposed to the API you have to create the rules you want to control with the API in the automation section of firewall menu option 
![image](https://github.com/user-attachments/assets/9eb383b3-1087-4396-b8c0-dfde63959180)
