### ISSUE TITLE
Add Tab log file view

### ISSUE THREAD

**Issue by Vincenzoferrara** [Red-Swingline/OPNsenseManager#23]
I have traffic under 5 vlan, when something is not going as it should the first thing I see are the logs.

I would like it to be added, it is located in firewall > rules > log files > Live

Is this implementation planned?

Another small question, maybe off topic, but how do you update this app? Does it notify you if there is a new update from GitHub? Or does one have to search for it manually? If you haven't used any update system you might want to check out vikunja android, They have implemented a GitHub based update system

**Comment by Red-Swingline** [comment]
Looks easy enough to add so I will add it this coming weekend.

I dot currently have a update system in place, I just do releases here and hopefully people find it. I'll take a look at vikunja thanks for the tip.

**Comment by Red-Swingline** [comment]
Testing now but should push a release tonight should display nicely on any screen size

<img src="https://github.com/user-attachments/assets/f6ee989d-cc90-4aa2-81e1-38851745893a" alt="1000000482" width="300"/>

<img src="https://github.com/user-attachments/assets/318b8f9c-8616-4ea1-bda3-0f02d5890e77" alt="1000000479" width="300"/>

<img src="https://github.com/user-attachments/assets/14fb9abf-5d7a-4420-8d42-175d38b62609" alt="image" width="300"/>
