### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by PsycoStea** [Red-Swingline/OPNsenseManager#28]
Is there a more detailed list of instructions on how to connect the app the OPNsense?

**Comment by hashnag** [comment]
It's pretty straight forward. Follow the example in the images on the main page. Your key/secret will be inside the file that's downloaded from the OPNsense GUI when you create your token. To create your token go to System>Access>Users probably preferably create a new user, add a token and then add the Effective Privileges as described on the main page. The URL is just the FQDN of your device or IP address (eg https://opnsense.mynetwork.home or whatever). Set a pin and you're done! FWIW, the token/key tripped me up (I generated a OTP thinking that was it...) until I finally looked at the file generated when creating the token. Great project PsycoStea! Merry Christmas! And thanks so much for sharing!

**Comment by PsycoStea** [comment]
Thanks for the info!
