### ISSUE TITLE
Rule list is empty 

### ISSUE THREAD

**Issue by Gis70** [Red-Swingline/OPNsenseManager#8]
Hello,

I'm just testing your app to manage easily some access or not to internet about some devices but rule list stay empty.
I don't know how to help to debug. (Except with Android studio maybe ?)

**Comment by Red-Swingline** [comment]
I thought this was in the readme, but there isn't an API method to manage standard rules. You need to install the firewall plugin and recreate the rules that you would like to control from the app [](https://docs.opnsense.org/development/api/plugins/firewall.html) 

It is possible to create rules using the API using this plugin, but it's not implemented in this app.

**Comment by Red-Swingline** [comment]
I'm going to close this assuming that you got this working with the correct firewall plugin.
