### ISSUE TITLE
Explanation on how to connect?

### ISSUE THREAD

**Issue by nerlins** [Red-Swingline/OPNsenseManager#9]
I am new to API usage with OPNsense, so maybe this is obvious. I have entered the key and secret, but I cannot connect. I have tried URL/IP as 172.24.0.1 or https://172.24.0.1, and port as 443. I am not otherwise sure how to connect, and it keeps saying invalid URL. Is that the correct port and URL method? Please let me know.

**Comment by Red-Swingline** [comment]
Check the new release https://github.com/Red-Swingline/OPNsenseManager/releases/tag/v1.0.7-Beta

**Comment by nerlins** [comment]
I didn't get a chance to answer you quick enough, before you close the issue. I should be running the most updated version of open sense. I know updated the system within the past couple of weeks. I'll make sure and download the new app and try again this evening.

**Comment by nerlins** [comment]
I've got it connected now. Thanks a bunch.

**Comment by Red-Swingline** [comment]
Glad you got it connected. I hope it's helpful.
